### PR TITLE
Added Cheat.sh to README.md 

### LINKED ISSUE #90: Cheat.sh
Cheat.sh is a great way for getting a cheatsheet right in the terminal as well as on a browser with tons of documentation and also has a light network footprint.

### PR DESCRIPTION
**Pull request by JiteshKanojia**
Resolve #90

### CODE REVIEW

**Comment by GowthamGoush** [comment]
@JiteshKanojia, kindly create an issue before raising a pull request.

**Comment by JiteshKanojia** [comment]
> @JiteshKanojia, kindly create an issue before raising a pull request.

Okay will do. 😄

**Comment by GowthamGoush** [comment]
Great job, but one last step, kindly mention ` resolve #issue_number` in the description.

**Comment by JiteshKanojia** [comment]
> Great job, but one last step, kindly mention ` resolve #issue_number` in the description.

Done 👍

**Pull request merged**
