### PR TITLE
added dev.to

### LINKED ISSUE #40: dev.to
**DEV** is a type of Blogging community of software developers for getting together to help one another out. A platform where everyone can share and discover great ideas, having debate and making friends.  It is a blogging platform? A chat room? A forum? All 3 things combined. 

**Link to website** - https://dev.to/

### PR DESCRIPTION
**Pull request by DevyaniJain13**
resolve #40

### CODE REVIEW

**Review by GowthamGoush — COMMENTED** [review]
Hey, @DevyaniJain13, great job! But before we could merge, could you please consider making the description a bit short?

**Comment by DevyaniJain13** [comment]
> Hey, @DevyaniJain13, great job! But before we could merge, could you please consider making the description a bit short?

Yes, I will do it . Thanks for considering !!

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged!

**Comment by GowthamGoush** [comment]
Since the description was a bit lengthy, I added few changes to make it concise. Also, thanks for the contribution!

**Pull request merged**
