### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by nayan2306**
I have down with image upload now doing readme updated

### CODE REVIEW

**Comment by GowthamGoush** [comment]
@nayan2306, it seems like you haven't pushed any changes. Kindly look into it, please.

**Comment by GowthamGoush** [comment]
Also, please do mention `resolve #issue_number`

**Comment by nayan2306** [comment]
issue resolve #137

**Comment by GowthamGoush** [comment]
> issue resolve #137

@nayan2306, kindly mention the `issue_number`. The above mentioned is a pull request number.

**Pull request merged**
