### PR TITLE
Add wttr 

### LINKED ISSUE #105: wttr
click 👇
[wttr](https://wttr.in)
- wttr is a console-oriented weather forecast service that supports various information representation methods like terminal-oriented ANSI-sequences for console HTTP clients (curl, httpie, or wget), HTML for web browsers, or PNG for graphical viewers.
- It uses wego for visualization and various data sources for weather forecast information.

### PR DESCRIPTION
**Pull request by MayankRawat06**
Resolve #105

### CODE REVIEW

**Comment by GowthamGoush** [comment]
@MayankRawat06, kindly create an issue before raising a pull request.

**Comment by MayankRawat06** [comment]
How i should be going on with it, I'm an absolute beginner, kindly help :(

**Comment by MayankRawat06** [comment]
How i should be going on with it, I'm an absolute beginner, kindly help :(

**Comment by GowthamGoush** [comment]
> How i should be going on with it, I'm an absolute beginner, kindly help :(

Hey, @MayankRawat06, no problem, we are here to help you out.
Just head over to the issues section and add the title & description in the mentioned format.
For a more precise idea, check this successfully closed issue - #46

**Comment by MayankRawat06** [comment]
Thanks a lot for helping @GowthamGoush.

**Comment by GowthamGoush** [comment]
> Thanks a lot for helping @GowthamGoush.

Always welcome. Keep hacking!!

**Pull request merged**
