### PR TITLE
Add  FreeCodeCamp

### LINKED ISSUE #76: freecodecamp.org
Free Code Camp is a great place to start learning new technologies. It is free and open-source and is accessible to anyone. Their Youtube channel has content in all fields and is helpful to all new and experienced developers. Overall, I think it's a site to be featured in this repo.

### PR DESCRIPTION
**Pull request by BirajCoder**
resolve #76

### CODE REVIEW

**Comment by BirajCoder** [comment]
I am sorry I did the other change in the same branch before the main branch was merged. Please let me know if I have to change something.

**Comment by GowthamGoush** [comment]
@BirajCoder, it seems like many unnecessary changes have been added to the readme. So kindly create a new pull request with an updated forked repository.

**Comment by BirajCoder** [comment]
Sure, I will make a new fork and do different updates in different branches.

**Comment by GowthamGoush** [comment]
> Sure, I will make a new fork and do different updates in different branches.

Sure, @BirajCoder, thanks for your patience!

**Pull request closed without merging**
