### PR TITLE
Added Astronomy Picture of the Day

### LINKED ISSUE #126: Astronomy Picture of the Day
Discover a different image of our universe every day.

https://apod.nasa.gov/apod/astropix.html

### PR DESCRIPTION
**Pull request by EgonMarmol**
resolve #126

### CODE REVIEW

**Comment by Rangaraj-baskar** [comment]
Can you edit the PR without use of formatter !

**Comment by EgonMarmol** [comment]
@Rangaraj-baskar What formatter do you mean?

**Review by Rangaraj-baskar — CHANGES_REQUESTED** [review]
image

Kindly look into these changes made by your PR apart from your contribution

**Comment by EgonMarmol** [comment]
@Rangaraj-baskar Apologies! I was not aware of that. I hope the changes does the trick.

**Review by Rangaraj-baskar — APPROVED** [review]

**Pull request merged**
