### PR TITLE
JitterVideo

### PR DESCRIPTION
**Pull request by Shreyalytical**
resolve issue #24

### CODE REVIEW

**Review by GowthamGoush — APPROVED** [review]
Ready to be merged!

**Comment by GowthamGoush** [comment]
Thanks for the contribution, @Shreyalytical!

**Comment by Shreyalytical** [comment]
> Thanks for the contribution, @Shreyalytical!

"Would love to collaborate and contribute more in future 💯 "

**Comment by GowthamGoush** [comment]
> > Thanks for the contribution, @Shreyalytical!
> 
> "Would love to collaborate and contribute more in future 💯 "

Glad to hear that, @Shreyalytical 🙌  Also, you may add as many websites as you wish.

**Pull request merged**
